// <auto-generated />
using HashMaker.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HashMaker5.Migrations
{
    [DbContext(typeof(HashingContext))]
    [Migration("20210426200152_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HashMaker.Database.PasswordHash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HashSha256")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashSha384")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashSha512")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PasswordHashes");
                });

            modelBuilder.Entity("HashMaker.Database.ProcessingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NextPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NoOfProcessedPasswords")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ProcessingInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
